name: Frontend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Inspector de Frontend
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Clonar el repositorio
        uses: actions/checkout@v4

      - name: ⚙️ Configurar Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 📦 Instalar dependencias
        run: npm install --legacy-peer-deps

      - name: 🔨 Construir Vite
        env:
          VITE_API_URL: "http://localhost:3000/api"
          VITE_SENTRY_DSN: "[https://dummy@sentry.io/0](https://dummy@sentry.io/0)"
        run: npm run build
      
      - name: 🚀 Notificar a EasyPanel (despliegue FrontEnd)
        if: success()
        run: |
          curl -X POST "http://49.13.19.148:3000/api/deploy/84658667fbbbfedc72b29a441d8690b78afc71392db5c567"

